version: "3.8"

services:

  angular-app: 
    build:
      context: ./angular-app/
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - express-server
  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - express-server
  express-server:
    build:
      context: ./express-server/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:

      MONGO_INITDB_DATABASE: mydatabase

volumes:
  mongo-data: 
